name: Backend Test

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
    paths:
      - "backend/*"

jobs:
  go-static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
          cache: true
      - name: Verify go.mod is tidy
        working-directory: ./backend
        run: |
          go mod tidy -go=1.23
          git diff --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --verbose --timeout=3m
          skip-cache: true
          working-directory: ./backend

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
          cache: true
      - name: Run all tests
        working-directory: ./backend
        run: make test
